# ABOUTME: Core WaveSpeed AI nodes for ComfyUI (API client, video preview, audio save, image upload).
# ABOUTME: Provides authentication, media download/preview, and image upload to WaveSpeed AI API.

import os
import time
import configparser

from comfy_api.latest import IO

# Configuration handling
try:
    current_dir = os.path.dirname(os.path.abspath(__file__))
    temp_dir = os.path.join(current_dir, '.temp')
    if not os.path.exists(temp_dir):
        os.makedirs(temp_dir)

    config_path = os.path.join(current_dir, 'config.ini')
    config = configparser.ConfigParser()

    if not os.path.exists(config_path):
        config['API'] = {'WAVESPEED_API_KEY': ''}
        with open(config_path, 'w') as config_file:
            config.write(config_file)

    config.read(config_path)
except Exception as e:
    print(f"[WaveSpeed] Error reading or creating config file: {e}")
    config = None


class WaveSpeedAIAPIClient(IO.ComfyNode):
    """
    WaveSpeed AI API Client Node

    This node creates a client for connecting to the WaveSpeed AI API.
    It can use an API key from the input or from the config.ini file.
    """

    @classmethod
    def define_schema(cls):
        return IO.Schema(
            node_id="WaveSpeedAIAPIClient",
            display_name="WaveSpeed Client",
            category="ERPK/WaveSpeedAI",
            inputs=[
                IO.String.Input("api_key", optional=True, default="",
                                tooltip="WaveSpeed AI API key. If empty, checks ComfyUI Settings, then WAVESPEED_API_KEY environment variable, then config.ini"),
            ],
            outputs=[
                IO.Custom("WAVESPEED_AI_API_CLIENT").Output("client"),
            ],
        )

    @classmethod
    def execute(cls, api_key="", **kwargs):
        wavespeed_api_key = ""

        # Priority 1: ComfyUI Settings
        try:
            from ..settings import get_comfy_setting
            settings_key = get_comfy_setting("ERPK.WAVESPEED_API_KEY")
            if settings_key:
                wavespeed_api_key = settings_key
                print("[WaveSpeed] Using API key from ComfyUI Settings")
        except (ImportError, ValueError):
            pass

        # Priority 2: Direct input
        if not wavespeed_api_key and api_key and api_key.strip():
            wavespeed_api_key = api_key.strip()
            print("[WaveSpeed] Using API key from node input")

        # Priority 3 & 4: Environment variable, then config file
        if not wavespeed_api_key:
            env_key = os.getenv("WAVESPEED_API_KEY", "").strip()
            if env_key:
                wavespeed_api_key = env_key
                print("[WaveSpeed] Using API key from environment variable WAVESPEED_API_KEY")
            elif config:
                try:
                    config_key = config['API']['WAVESPEED_API_KEY'].strip()
                    if config_key:
                        wavespeed_api_key = config_key
                        print("[WaveSpeed] Using API key from config.ini")
                    else:
                        raise ValueError(
                            "No API key found. Please provide via:\n"
                            "  1. ComfyUI Settings (Settings > ERPK > API Keys)\n"
                            "  2. Node input parameter\n"
                            "  3. WAVESPEED_API_KEY environment variable\n"
                            "  4. config.ini file"
                        )
                except KeyError:
                    raise ValueError(
                        "No API key found. Please provide via:\n"
                        "  1. ComfyUI Settings (Settings > ERPK > API Keys)\n"
                        "  2. Node input parameter\n"
                        "  3. WAVESPEED_API_KEY environment variable\n"
                        "  4. config.ini file"
                    )
            else:
                raise ValueError(
                    "No API key found. Please provide via:\n"
                    "  1. ComfyUI Settings (Settings > ERPK > API Keys)\n"
                    "  2. Node input parameter\n"
                    "  3. WAVESPEED_API_KEY environment variable\n"
                    "  4. config.ini file"
                )

        if not wavespeed_api_key:
            raise ValueError(
                "No API key found. Please provide via:\n"
                "  1. ComfyUI Settings (Settings > ERPK > API Keys)\n"
                "  2. Node input parameter\n"
                "  3. WAVESPEED_API_KEY environment variable\n"
                "  4. config.ini file"
            )

        return IO.NodeOutput({"api_key": wavespeed_api_key})


class PreviewVideo(IO.ComfyNode):
    """
    Preview Video Node for ComfyUI

    This node allows previewing and saving videos generated by WaveSpeed AI.
    """

    @classmethod
    def define_schema(cls):
        return IO.Schema(
            node_id="PreviewVideo",
            display_name="WaveSpeed Preview Video",
            category="ERPK/WaveSpeedAI",
            inputs=[
                IO.String.Input("video_url",
                                tooltip="URL of the video to preview and save"),
                IO.String.Input("save_file_prefix", default="wavespeed_video",
                                tooltip="Prefix for the saved video file"),
            ],
            outputs=[
                IO.String.Output("file_path"),
            ],
            is_output_node=True,
        )

    @classmethod
    def execute(cls, video_url, save_file_prefix, **kwargs):
        from utils.safe_fetch import fetch_remote_bytes
        try:
            import folder_paths
        except ImportError:
            class folder_paths:
                @staticmethod
                def get_output_directory():
                    return os.path.join(os.path.dirname(__file__), "output")

        if not video_url:
            raise ValueError("No video URL provided")

        try:
            video_data = fetch_remote_bytes(
                video_url,
                max_bytes=500 * 1024 * 1024,
                timeout=60,
                user_agent="ERPK-WaveSpeed-PreviewVideo/1.0",
            )
        except (ValueError, IOError) as e:
            raise RuntimeError(f"Error downloading video: {e}")

        file_extension = os.path.splitext(video_url)[-1].lower()
        if not file_extension or file_extension == '.' or len(file_extension) > 5:
            file_extension = '.mp4'

        from utils.safe_path import safe_filename_prefix
        output_dir = folder_paths.get_output_directory()
        safe_prefix = safe_filename_prefix(save_file_prefix, default="wavespeed_video")
        filename = f"{safe_prefix}_{int(time.time())}{file_extension}"
        file_path = os.path.join(output_dir, filename)

        with open(file_path, "wb") as f:
            f.write(video_data)

        print(f"[WaveSpeed] Video saved to: {file_path}")

        return IO.NodeOutput(file_path, ui={"video_url": [video_url]})


class SaveAudio(IO.ComfyNode):
    """
    Save Audio Node for ComfyUI

    This node allows saving audio files generated by WaveSpeed AI.
    """

    @classmethod
    def define_schema(cls):
        return IO.Schema(
            node_id="SaveAudio",
            display_name="WaveSpeed Save Audio",
            category="ERPK/WaveSpeedAI",
            inputs=[
                IO.String.Input("audio_url",
                                tooltip="URL of the audio to download and save"),
                IO.String.Input("save_file_prefix", default="wavespeed_audio",
                                tooltip="Prefix for the saved audio file"),
            ],
            outputs=[
                IO.String.Output("file_path"),
            ],
            is_output_node=True,
        )

    @classmethod
    def execute(cls, audio_url, save_file_prefix, **kwargs):
        from utils.safe_fetch import fetch_remote_bytes
        try:
            import folder_paths
        except ImportError:
            class folder_paths:
                @staticmethod
                def get_output_directory():
                    return os.path.join(os.path.dirname(__file__), "output")

                @staticmethod
                def get_save_image_path(prefix, directory):
                    filename = f"{prefix}_{int(time.time())}"
                    return directory, filename, 0, None, None

        if not audio_url:
            raise ValueError("No audio URL provided")

        try:
            audio_data = fetch_remote_bytes(
                audio_url,
                max_bytes=100 * 1024 * 1024,
                timeout=60,
                user_agent="ERPK-WaveSpeed-SaveAudio/1.0",
            )
        except (ValueError, IOError) as e:
            raise RuntimeError(f"Error downloading audio: {e}")

        file_extension = os.path.splitext(audio_url)[-1].lower()
        if not file_extension or file_extension == '.' or len(file_extension) > 5:
            file_extension = '.mp3'

        full_output_folder, filename, counter, _, _ = folder_paths.get_save_image_path(
            save_file_prefix,
            folder_paths.get_output_directory()
        )

        file = f"{filename}_{counter:05d}{file_extension}"
        file_path = os.path.join(full_output_folder, file)

        with open(file_path, "wb") as f:
            f.write(audio_data)

        print(f"[WaveSpeed] Audio saved to: {file_path}")

        return IO.NodeOutput(file_path)


class UploadImage(IO.ComfyNode):
    """
    Upload Image Node for WaveSpeed AI

    This node uploads images to WaveSpeed AI and returns the URL.
    Note: Uploaded URLs expire after a short time.
    """

    DESCRIPTION = "Upload image(s) to WaveSpeed AI API. The URL expires after a short time. Use 'single_image_url' for nodes expecting one image, 'all_image_urls' for batch processing."

    @classmethod
    def define_schema(cls):
        return IO.Schema(
            node_id="UploadImage",
            display_name="WaveSpeed Upload Image",
            category="ERPK/WaveSpeedAI",
            description=cls.DESCRIPTION,
            inputs=[
                IO.Image.Input("image", tooltip="Image(s) to upload to WaveSpeed AI"),
                IO.Custom("WAVESPEED_AI_API_CLIENT").Input("client", optional=True,
                    tooltip="WaveSpeed API client (optional if API key is configured in Settings)"),
            ],
            outputs=[
                IO.String.Output("single_image_url"),
                IO.String.Output("all_image_urls"),
            ],
        )

    @classmethod
    def execute(cls, image, client=None, **kwargs):
        from .wavespeed_api.client import WaveSpeedClient
        from .wavespeed_api.utils import tensor2images

        if client is None:
            client = WaveSpeedAIAPIClient.execute()[0]

        images = tensor2images(image)
        image_urls = []

        real_client = WaveSpeedClient(api_key=client["api_key"])
        for img in images:
            image_url = real_client.upload_file(img)
            image_urls.append(image_url)
            print(f"[WaveSpeed] Image uploaded: {image_url}")

        return IO.NodeOutput(
            image_urls[0] if image_urls else "",
            image_urls,
        )
